import { message } from "../../types/message";
import { Context, createContext } from "react";

export const TestMassagesData: Context<message[]> = createContext<message[]>([
  {
    id: "Keter",
    timestamp: new Date(),
    author: {
      id: "0",
      user_name: "ゼっちゃん",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "王冠",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
  {
    id: "Chokohmah",
    timestamp: new Date(),
    author: {
      id: "1",
      user_name: "弟子1号",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "知恵",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
  {
    id: "Binah",
    timestamp: new Date(),
    author: {
      id: "2",
      user_name: "2号兄貴",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "理解",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
  {
    id: "Chesed",
    timestamp: new Date(),
    author: {
      id: "0",
      user_name: "ゼっちゃん",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "慈悲",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
  {
    id: "Gevurah",
    timestamp: new Date(),
    author: {
      id: "1",
      user_name: "弟子1号",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "峻厳",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
  {
    id: "Tiphereth",
    timestamp: new Date(),
    author: {
      id: "1",
      user_name: "弟子1号",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "美",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
  {
    id: "Netzach",
    timestamp: new Date(),
    author: {
      id: "0",
      user_name: "ゼっちゃん",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "勝利",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
  {
    id: "Hod",
    timestamp: new Date(),
    author: {
      id: "2",
      user_name: "2号兄貴",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "栄光",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
  {
    id: "Yesod",
    timestamp: new Date(),
    author: {
      id: "1",
      user_name: "弟子1号",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "基礎",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
  {
    id: "Malkuth",
    timestamp: new Date(),
    author: {
      id: "0",
      user_name: "ゼっちゃん",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "王国",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
  {
    id: "Ba'at",
    timestamp: new Date(),
    author: {
      id: "0",
      user_name: "ゼっちゃん",
      avatar: "",
      bot: false,
      state: 0,
    },
    content: "知識",
    guild_id: "server_one",
    channel_id: "a",
    edited_timestamp: new Date(),
  },
]);
