import { myInfo, user } from "../../types/user";
import { Context, createContext } from "react";

export const TestUserData: Context<user> = createContext<user>({
  id: "0",
  name: "ゼっちゃん",
  avatar: "",
  bot: false,
  state: 0,
});

export const testMyInfo: myInfo = {
  id: "0",
  name: "ゼっちゃん",
  avatar: "",
  bot: false,
  state: 0,
  guilds: [
    {
      id: "server_one",
      name: "鯖1",
      topic: "星1とは違います",
      icon: "",
      created_at: "",
      updated_at: "",
      deleted_at: "",

      channels: [
        {
          id: "a",
          name: "spaceA",
          topics: "this is A",
          type: "text",
          position: 0,
          latest_message_id: "aaa",
          created_at: "aaa",
          updated_at: "",
          deleted_at: "",
          guildId: "server_one",
        },
        {
          id: "b",
          name: "spaceB",
          topics: "this is B",
          type: "text",
          position: 1,
          latest_message_id: "bbb",
          created_at: "bbb",
          updated_at: "",
          deleted_at: "",
          guildId: "server_one",
        },
      ],
    },
    {
      id: "server_two",
      name: "鯖2",
      topic: "星2とは違います",
      icon: "",
      created_at: "",
      updated_at: "",
      deleted_at: "",

      channels: [
        {
          id: "c",
          name: "spaceC",
          topics: "this is C",
          type: "text",
          position: 0,
          latest_message_id: "ccc",
          created_at: "ccc",
          updated_at: "",
          deleted_at: "",
          guildId: "server_two",
        },
        {
          id: "d",
          name: "spaceD",
          topics: "this is D",
          type: "text",
          position: 1,
          latest_message_id: "ddd",
          created_at: "ddd",
          updated_at: "",
          deleted_at: "",
          guildId: "server_two",
        },
      ],
    },
  ],
};

export const preMember: user[] = [
  {
    id: "0",
    name: "ゼっちゃん",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "1",
    name: "弟子1号",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "2",
    name: "2号兄貴",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "3",
    name: "ゼっちゃん",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "4",
    name: "弟子1号",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "5",
    name: "ゼっちゃん",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "6",
    name: "弟子1号",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "7",
    name: "2号兄貴",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "8",
    name: "ゼっちゃん",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "9",
    name: "弟子1号",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "10",
    name: "2号兄貴",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "11",
    name: "ゼっちゃん",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "13",
    name: "弟子1号",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "14",
    name: "2号兄貴",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "15",
    name: "ゼっちゃん",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "16",
    name: "弟子1号",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "17",
    name: "ゼっちゃん",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "18",
    name: "弟子1号",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "19",
    name: "2号兄貴",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "20",
    name: "ゼっちゃん",
    avatar: "",
    bot: false,
    state: 0,
  },
  {
    id: "3141592653589792384",
    name: "弟子1号",
    avatar: "",
    bot: false,
    state: 0,
  },
];
