import { myInfo, user } from "../../types/user";
import { Context, createContext } from "react";

export const TestUserData: Context<user> = createContext<user>({
  id: "0",
  name: "ゼっちゃん",
  avatar: "",
  bot: false,
  state: 0,
});

export const testMyInfo: myInfo = {
  id: "0",
  name: "ゼっちゃん",
  avatar: "",
  bot: false,
  state: 0,
  guilds: [
    {
      id: "server_one",
      name: "鯖1",
      topic: "星1とは違います",
      icon: "",
      owner_id: "0",
      users: [
        {
          id: "0",
          name: "ゼっちゃん",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "1",
          name: "弟子1号",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "2",
          name: "2号兄貴",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "3",
          name: "ゼっちゃん",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "4",
          name: "弟子1号",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "5",
          name: "ゼっちゃん",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "6",
          name: "弟子1号",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "7",
          name: "2号兄貴",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "8",
          name: "ゼっちゃん",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "9",
          name: "弟子1号",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "10",
          name: "2号兄貴",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "11",
          name: "ゼっちゃん",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "13",
          name: "弟子1号",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "14",
          name: "2号兄貴",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "15",
          name: "ゼっちゃん",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "16",
          name: "弟子1号",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "17",
          name: "ゼっちゃん",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "18",
          name: "弟子1号",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "19",
          name: "2号兄貴",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "20",
          name: "ゼっちゃん",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "1145141919810",
          name: "弟子1号",
          avatar: "",
          bot: false,
          state: 0,
        },
      ],
      channels: [
        {
          id: "a",
          channel_name: "spaceA",
          channel_topics: "this is A",
          channel_type: "text",
          channel_position: 0,
          creator_id: "0",
        },
        {
          id: "b",
          channel_name: "spaceB",
          channel_topics: "this is B",
          channel_type: "text",
          channel_position: 1,
          creator_id: "0",
        },
      ],
    },
    {
      id: "server_two",
      name: "鯖2",
      topic: "星2とは違います",
      icon: "",
      owner_id: "0",
      users: [
        {
          id: "0",
          name: "ゼっちゃん",
          avatar: "",
          bot: false,
          state: 0,
        },
        {
          id: "1",
          name: "弟子1号",
          avatar: "",
          bot: false,
          state: 0,
        },
      ],
      channels: [
        {
          id: "c",
          channel_name: "spaceC",
          channel_topics: "this is C",
          channel_type: "text",
          channel_position: 0,
          creator_id: "0",
        },
        {
          id: "d",
          channel_name: "spaceD",
          channel_topics: "this is D",
          channel_type: "text",
          channel_position: 1,
          creator_id: "0",
        },
      ],
    },
  ],
};
